export class Consts {
    static WEEKDAYS_JP = ["日", "月", "火", "水", "木", "金", "土"];
    static WEEKDAYS_EN = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];
    static SEKKI = ["春分", "清明", "穀雨", "立夏", "小満", "芒種", "夏至", "小暑", "大暑", "立秋", "処暑", "白露", "秋分", "寒露", "霜降", "立冬", "小雪", "大雪", "冬至", "小寒", "大寒", "立春", "雨水", "啓蟄"];
    static JUNICHOKU = ["たつ", "のぞく", "みつ", "たいら", "さだん", "とる", "やぶる", "あやぶ", "なる", "おさん", "ひらく", "とづ"];
    static JUNISHI = ["ね", "うし", "とら", "う", "たつ", "み", "うま", "ひつじ", "さる", "とり", "いぬ", "い"];
    static JIKKAN = ["きのえ", "きのと", "ひのえ", "ひのと", "つちのえ", "つちのと", "かのえ", "かのと", "みずのえ", "みずのと"];
    static KYUSEI = ["一白", "二黒", "三碧", "四緑", "五黄", "六白", "七赤", "八白", "九紫"];
    static MAMBAINICHI = [[1, 6], [2, 9], [0, 3], [3, 4], [5, 6], [9, 6], [0, 7], [3, 8], [9, 6], [9, 10], [11, 0], [3, 0]];
    static SANRIMBOU = [11, 2, 6];
    static FUJOJU = [[3, 11, 19, 27], [2, 10, 18, 26], [1, 9, 17, 25], [4, 12, 20, 28], [5, 13, 21, 29], [6, 14, 22, 30]];
    static SHUKU = [
        {name: "角", desc: "着始め・柱立て・普請造作・結婚は吉。葬式は凶。"},
        {name: "亢", desc: "衣類仕立て・物品購入・種蒔きは吉。造作は凶。"},
        {name: "氐", desc: "結婚・開店・結納・酒造りは吉。着始めは凶。"},
        {name: "房", desc: "髪切り・結婚・旅行・移転・開店・祭祀は吉。"},
        {name: "心", desc: "祭祀・移転・旅行・新規事は吉。造作と結婚は凶。盗難注意。"},
        {name: "尾", desc: "結婚・開店・移転・造作・新規事は吉。着始めと仕立ては凶。"},
        {name: "箕", desc: "動土・池掘り・仕入れ・集金・改築は吉。結婚と葬式は凶。"},
        {name: "斗", desc: "土掘り・開店・造作は吉。"},
        {name: "牛", desc: "移転・旅行・金談など全てが吉。"},
        {name: "女", desc: "稽古始めとお披露目は吉。訴訟・結婚・葬式は凶。"},
        {name: "虚", desc: "着始めと学問始めは吉。相談・造作・積極的な行動は凶。"},
        {name: "危", desc: "壁塗り・船普請・酒作りは吉。衣類仕立てと高所作業は凶。"},
        {name: "室", desc: "祈願始め・結婚・祝い事・祭祀・井戸掘りは吉。"},
        {name: "壁", desc: "開店・旅行・結婚・衣類仕立て・新規事開始は吉。"},
        {name: "奎", desc: "開店・文芸開始・樹木植替えは吉。"},
        {name: "婁", desc: "動土・造作・縁談・契約・造園・衣類仕立ては吉。"},
        {name: "胃", desc: "開店・移転・求職は吉。"},
        {name: "昴", desc: "神仏詣・祝い事・開店は吉。"},
        {name: "畢", desc: "稽古始めと運搬始めは吉。造作と衣類着始めは凶。"},
        {name: "觜", desc: "稽古始めと運搬始めは吉。造作と衣類着始めは凶。"},
        {name: "参", desc: "仕入れ・納入・取引開始・祝い事・縁談は吉。"},
        {name: "井", desc: "神仏詣・種蒔き・動土・普請は吉。衣類仕立ては凶。"},
        {name: "鬼", desc: "婚礼のみ凶。他の事は全て吉。"},
        {name: "柳", desc: "物事を断るのは吉。結婚・開店・葬式は凶。"},
        {name: "星", desc: "乗馬始めと便所改造は吉。祝い事と種蒔きは凶。"},
        {name: "張", desc: "就職・見合い・神仏祈願・祝い事は吉。"},
        {name: "翼", desc: "耕作始め・植え替え・種蒔きは吉。高所作業と結婚は凶。"},
        {name: "軫", desc: "地鎮祭・落成式・祭祀・祝い事は吉。衣類仕立ては凶。"},
    ];
    static NANAJUNIKOU = [
        {no: 10, name: "雀始巣", yomi: "すずめはじめてすくう", desc: "雀が巣を構え始める"},
        {no: 11, name: "桜始開", yomi: "さくらはじめてひらく", desc: "桜の花が咲き始める"},
        {no: 12, name: "雷乃発声", yomi: "かみなりすなわちこえをはっす", desc: "遠くで雷の音がし始める"},
        {no: 13, name: "玄鳥至", yomi: "つばめきたる", desc: "燕が南からやって来る"},
        {no: 14, name: "鴻雁北", yomi: "こうがんきたへかえる", desc: "雁が北へ渡って行く"},
        {no: 15, name: "虹始見", yomi: "にじはじめてあらわる", desc: "雨の後に虹が出始める"},
        {no: 16, name: "葭始生", yomi: "あしはじめてしょうず", desc: "葦が芽を吹き始める"},
        {no: 17, name: "霜止出苗", yomi: "しもやんでなえいづる", desc: "霜が終り稲の苗が生長する"},
        {no: 18, name: "牡丹華", yomi: "ぼたんはなさく", desc: "牡丹の花が咲く"},
        {no: 19, name: "蛙始鳴", yomi: "かわずはじめてなく", desc: "蛙が鳴き始める"},
        {no: 20, name: "蚯蚓出", yomi: "みみずいづる", desc: "蚯蚓が地上に這出る"},
        {no: 21, name: "竹笋生", yomi: "たけのこしょうず", desc: "筍が生えて来る"},
        {no: 22, name: "蚕起食桑", yomi: "かいこおきてくわをはむ", desc: "蚕が桑を盛んに食べ始める"},
        {no: 23, name: "紅花栄", yomi: "べにばなさかう", desc: "紅花が盛んに咲く"},
        {no: 24, name: "麦秋至", yomi: "むぎのときいたる", desc: "麦が熟し麦秋となる"},
        {no: 25, name: "螳螂生", yomi: "かまきりしょうず", desc: "螳螂が生まれ出る"},
        {no: 26, name: "腐草為蛍", yomi: "くされたるくさほたるとなる", desc: "腐った草が蒸れ蛍になる"},
        {no: 27, name: "梅子黄", yomi: "うめのみきばむ", desc: "梅の実が黄ばんで熟す"},
        {no: 28, name: "乃東枯", yomi: "なつかれくさかるる", desc: "夏枯草が枯れる"},
        {no: 29, name: "菖蒲華", yomi: "あやめはなさく", desc: "あやめの花が咲く"},
        {no: 30, name: "半夏生", yomi: "はんげしょうず", desc: "烏柄杓が生える"},
        {no: 31, name: "温風至", yomi: "あつかぜいたる", desc: "暖い風が吹いて来る"},
        {no: 32, name: "蓮始開", yomi: "はすはじめてひらく", desc: "蓮の花が開き始める"},
        {no: 33, name: "鷹乃学習", yomi: "たかすなわちわざをなす", desc: "鷹の幼鳥が飛ぶことを覚える"},
        {no: 34, name: "桐始結花", yomi: "きりはじめてはなをむすぶ", desc: "桐の花が(来年の)蕾をつける"},
        {no: 35, name: "土潤溽暑", yomi: "つちうるおうてむしあつし", desc: "土が湿って蒸暑くなる"},
        {no: 36, name: "大雨時行", yomi: "たいうときどきにふる", desc: "時として大雨が降る"},
        {no: 37, name: "涼風至", yomi: "すづかぜいたる", desc: "涼しい風が立ち始める"},
        {no: 38, name: "寒蝉鳴", yomi: "ひぐらしなく", desc: "蜩が鳴き始める"},
        {no: 39, name: "蒙霧升降", yomi: "ふかききりまとう", desc: "深い霧が立ち込める"},
        {no: 40, name: "綿柎開", yomi: "わたのはなしべひらく", desc: "綿を包む萼（がく）が開く"},
        {no: 41, name: "天地始粛", yomi: "てんちはじめてさむし", desc: "ようやく暑さが鎮まる"},
        {no: 42, name: "禾乃登", yomi: "こくものすなわちみのる", desc: "稲が実る"},
        {no: 43, name: "草露白", yomi: "くさのつゆしろし", desc: "草に降りた露が白く光る"},
        {no: 44, name: "鶺鴒鳴", yomi: "せきれいなく", desc: "鶺鴒（せきれい）が鳴き始める"},
        {no: 45, name: "玄鳥去", yomi: "つばめさる", desc: "燕が南へ帰って行く"},
        {no: 46, name: "雷乃収声", yomi: "かみなりすなわちこえをおさむ", desc: "雷が鳴り響かなくなる"},
        {no: 47, name: "蟄虫坏戸", yomi: "むしかくれてとをふさぐ", desc: "虫が土中に掘った穴をふさぐ"},
        {no: 48, name: "水始涸", yomi: "みずはじめてかる", desc: "田畑の水を干し始める"},
        {no: 49, name: "鴻雁来", yomi: "こうがんきたる", desc: "雁が飛来し始める"},
        {no: 50, name: "菊花開", yomi: "きくのはなひらく", desc: "菊の花が咲く"},
        {no: 51, name: "蟋蟀在戸", yomi: "きりぎりすとにあり", desc: "蟋蟀が戸の辺りで鳴く"},
        {no: 52, name: "霜始降", yomi: "しもはじめてふる", desc: "霜が降り始める"},
        {no: 53, name: "霎時施", yomi: "こさめときどきふる", desc: "小雨がしとしと降る"},
        {no: 54, name: "楓蔦黄", yomi: "もみじつたきばむ", desc: "もみじや蔦が黄葉する"},
        {no: 55, name: "山茶始開", yomi: "つばきはじめてひらく", desc: "山茶花が咲き始める"},
        {no: 56, name: "地始凍", yomi: "ちはじめてこおる", desc: "大地が凍り始める"},
        {no: 57, name: "金盞香", yomi: "きんせんかさく", desc: "水仙の花が咲く"},
        {no: 58, name: "虹蔵不見", yomi: "にじかくれてみえず", desc: "虹を見かけなくなる"},
        {no: 59, name: "朔風払葉", yomi: "きたかぜこのはをはらう", desc: "北風が木の葉を払い除ける"},
        {no: 60, name: "橘始黄", yomi: "たちばなはじめてきばむ", desc: "橘の実が黄色くなり始める"},
        {no: 61, name: "閉塞成冬", yomi: "そらさむくふゆとなる", desc: "天地の気が塞がって冬となる"},
        {no: 62, name: "熊蟄穴", yomi: "くまあなにこもる", desc: "熊が冬眠のために穴に隠れる"},
        {no: 63, name: "鱖魚群", yomi: "さけのうおむらがる", desc: "鮭が群がり川を上る"},
        {no: 64, name: "乃東生", yomi: "なつかれくさしょうず", desc: "夏枯草が芽を出す"},
        {no: 65, name: "麋角解", yomi: "おおしかのつのおつる", desc: "大鹿が角を落とす"},
        {no: 66, name: "雪下出麦", yomi: "ゆきわたりてむぎいづる", desc: "雪の下で麦が芽を出す"},
        {no: 67, name: "芹乃栄", yomi: "せりすなわちさかう", desc: "芹がよく生育する"},
        {no: 68, name: "水泉動", yomi: "しみずあたたかをふくむ", desc: "地中で凍った泉が動き始める"},
        {no: 69, name: "雉始雊", yomi: "きじはじめてなく", desc: "雄の雉が鳴き始める"},
        {no: 70, name: "款冬華", yomi: "ふきのはなさく", desc: "蕗の薹（ふきのとう）が蕾を出す"},
        {no: 71, name: "水沢腹堅", yomi: "さわみずこおりつめる", desc: "沢に氷が厚く張りつめる"},
        {no: 72, name: "鶏始乳", yomi: "にわとりはじめてとやにつく", desc: "鶏が卵を産み始める"},
        {no: 1, name: "東風解凍", yomi: "はるかぜこおりをとく", desc: "東風が厚い氷を解かし始める"},
        {no: 2, name: "黄鶯睍睆", yomi: "うぐいすなく", desc: "鶯が山里で鳴き始める"},
        {no: 3, name: "魚上氷", yomi: "うおこおりをいずる", desc: "割れた氷の間から魚が飛び出る"},
        {no: 4, name: "土脉潤起", yomi: "つちのしょううるおいおこる", desc: "雨が降って土が湿り気を含む"},
        {no: 5, name: "霞始靆", yomi: "かすみはじめてたなびく", desc: "霞がたなびき始める"},
        {no: 6, name: "草木萌動", yomi: "そうもくめばえいずる", desc: "草木が芽吹き始める"},
        {no: 7, name: "蟄虫啓戸", yomi: "すごもりむしとをひらく", desc: "冬籠りの虫が出て来る"},
        {no: 8, name: "桃始笑", yomi: "ももはじめてさく", desc: "桃の花が咲き始める"},
        {no: 9, name: "菜虫化蝶", yomi: "なむしちょうとなる", desc: "青虫が羽化して紋白蝶になる"},
    ];

    static MOON_AGE_NAME = [
        {deg: 36, name: "大潮"},
        {deg: 72, name: "中潮"},
        {deg: 108, name: "小潮"},
        {deg: 120, name: "長潮"},
        {deg: 132, name: "若潮"},
        {deg: 168, name: "中潮"},
        {deg: 216, name: "大潮"},
        {deg: 252, name: "中潮"},
        {deg: 288, name: "小潮"},
        {deg: 300, name: "長潮"},
        {deg: 312, name: "若潮"},
        {deg: 348, name: "中潮"},
        {deg: 360, name: "大潮"}
    ];

    static DEFAULT_HOLIDAYS = [
        {date: "01/01", name: "元日"},
        {date: "01/w2-1", name: "成人の日"},
        {date: "02/11", name: "建国記念の日"},
        {date: "02/23", name: "天皇誕生日"},
        {date: "04/29", name: "昭和の日"},
        {date: "05/03", name: "憲法記念日"},
        {date: "05/04", name: "みどりの日"},
        {date: "05/05", name: "こどもの日"},
        {date: "07/w3-1", name: "海の日"},
        {date: "08/11", name: "山の日"},
        {date: "09/w3-1", name: "敬老の日"},
        {date: "10/w2-1", name: "スポーツの日"},
        {date: "11/03", name: "文化の日"},
        {date: "11/23", name: "勤労感謝の日"}
    ];

    static ERAS = [
        {name: "令和", since: new Date(2019, 4, 1), until: null},
        {name: "平成", since: new Date(1989, 0, 7), until: new Date(2019, 3, 30)},
        {name: "昭和", since: new Date(1926, 11, 25), until: new Date(1989, 0, 7)},
        {name: "大正", since: new Date(1912, 6, 30), until: new Date(1926, 11, 24)},
        {name: "明治", since: new Date(1868, 0, 1), until: new Date(1912, 6, 29)},
    ];

    static EVENTS = {
        // 記念日 referred to https://zatsuneta.com/, https://www.nnh.to/, https://dic.nicovideo.jp/
        // 末尾コメントは主に制定年が不詳の場合の設定理由
        1: [
            {date: "01/01", onLunarCal: false, name: "初詣"},
            {date: "01/01", onLunarCal: false, name: "年賀"},
            {date: "01/01", onLunarCal: true, name: "旧元旦"},
            {date: "01/02", onLunarCal: false, name: "初夢"},
            {date: "01/02", onLunarCal: false, name: "書き初め"},
            {date: "01/06", onLunarCal: false, name: "六日年越し"},
            {date: "01/07", onLunarCal: false, name: "七草"},
            {date: "01/07", onLunarCal: true, name: "旧七草"},
            {date: "01/08", onLunarCal: false, name: "初薬師"},
            {date: "01/09", onLunarCal: false, name: "宵えびす"},
            {date: "01/10", onLunarCal: false, name: "十日えびす"},
            {date: "01/10", onLunarCal: false, name: "初金毘羅"},
            {date: "01/11", onLunarCal: false, name: "鏡開き"},
            {date: "01/11", onLunarCal: false, name: "歳開き"},
            {date: "01/11", onLunarCal: false, name: "上元・小豆粥"},
            {date: "01/13", onLunarCal: false, name: "初虚空蔵"},
            {date: "01/14", onLunarCal: false, name: "左義長"},
            {date: "01/15", onLunarCal: false, name: "小正月"},
            {date: "01/15", onLunarCal: true, name: "旧小正月"},
            {date: "01/16", onLunarCal: false, name: "藪入り"},
            {date: "01/16", onLunarCal: false, name: "閻魔詣り"},
            {date: "01/18", onLunarCal: false, name: "初観音"},
            {date: "01/20", onLunarCal: false, name: "二十日正月"},
            {date: "01/20", onLunarCal: true, name: "旧二十日正月"},
            {date: "01/21", onLunarCal: false, name: "初大師"},
            {date: "01/24", onLunarCal: false, name: "初地蔵"},
            {date: "01/25", onLunarCal: false, name: "初天神"},
            {date: "01/28", onLunarCal: false, name: "初不動"},
            {date: "01/31", onLunarCal: false, name: "晦日正月"},

            {date: "01/02", onLunarCal: false, name: "箱根駅伝・往路", since: 1956},
            {date: "01/03", onLunarCal: false, name: "箱根駅伝・復路", since: 1956},
            {date: "01/03", onLunarCal: false, name: "ひとみの日", since: 1951}, // コンタクトレンズ実用化年
            {date: "01/04+wd", onLunarCal: false, name: "官公庁御用始め", since: null},
            {date: "01/04+wd", onLunarCal: false, name: "取引所大発会", since: 1983},
            {date: "01/05", onLunarCal: false, name: "囲碁の日", since: 2013},
            {date: "01/05", onLunarCal: false, name: "魚河岸初競り", since: 1935},
            {date: "01/06", onLunarCal: false, name: "東京消防出初式", since: 1949},
            {date: "01/06", onLunarCal: false, name: "ケーキの日", since: 1879},
            {date: "01/07", onLunarCal: false, name: "千円札の日", since: 1950},
            {date: "01/08", onLunarCal: false, name: "平成改元の日", since: 1990},
            {date: "01/09", onLunarCal: false, name: "とんちの日", since: null},
            {date: "01/10", onLunarCal: false, name: "１１０番の日", since: 1985},
            {date: "01/10", onLunarCal: false, name: "明太子の日", since: 2007}, // Google検索の最古ページ
            {date: "01/11", onLunarCal: false, name: "塩の日", since: null},
            {date: "01/11", onLunarCal: false, name: "ＵＮＯの日", since: 2017},
            {date: "01/12", onLunarCal: false, name: "スキーの日", since: 1994},
            {date: "01/13", onLunarCal: false, name: "桜島の日", since: 1914},
            {date: "01/15", onLunarCal: false, name: "いちごの日", since: 2006}, // Google検索の最古ページ
            {date: "01/16", onLunarCal: false, name: "囲炉裏の日", since: 2010}, // Google検索の最古ページ
            {date: "01/17", onLunarCal: false, name: "阪神淡路大震災の日", since: 1995},
            {date: "01/17", onLunarCal: false, name: "防災とボランティアの日", since: 1996},
            {date: "01/17", onLunarCal: false, name: "おむすびの日", since: 2000},
            {date: "01/18", onLunarCal: false, name: "カップスターの日", since: 1975},
            {date: "01/19", onLunarCal: false, name: "のど自慢の日", since: 1946},
            {date: "S20"  , onLunarCal: false, name: "シマエナガの日", since: 1946},
            {date: "01/21", onLunarCal: false, name: "スイートピーの日", since: 2017},
            {date: "01/22", onLunarCal: false, name: "ジャズの日", since: 2001},
            {date: "01/22", onLunarCal: false, name: "カレーライスの日", since: 1982},
            {date: "01/23", onLunarCal: false, name: "電子メールの日", since: 1994},
            {date: "01/23", onLunarCal: false, name: "八甲田山の日", since: 1902},
            {date: "01/24", onLunarCal: false, name: "郵便制度施行記念日", since: 1871},
            {date: "01/24", onLunarCal: false, name: "ゴールドラッシュの日", since: 1875}, // gold rushという言葉が現れた頃
            {date: "01/25", onLunarCal: false, name: "主婦休みの日", since: 2009},
            {date: "01/25", onLunarCal: false, name: "ホットケーキの日", since: 2005},
            {date: "01/26", onLunarCal: false, name: "文化財防火デー", since: 1949},
            {date: "01/26", onLunarCal: false, name: "コラーゲンの日", since: 1960},
            {date: "01/27", onLunarCal: false, name: "国旗制定記念日", since: 1870},
            {date: "01/28", onLunarCal: false, name: "コピーライターの日", since: 2004}, // Google検索の最古ページ
            {date: "01/29", onLunarCal: false, name: "昭和基地開設記念日", since: 1957},
            {date: "01/30", onLunarCal: false, name: "巡音ルカ記念日", since: 2009},
            {date: "01/31", onLunarCal: false, name: "愛菜の日", since: 2010}, // Google検索の最古ページ
            {date: "01/31", onLunarCal: false, name: "焼きビーフンの日", since: 2020},
        ],
        2: [
            {date: "02/02", onLunarCal: true, name: "二日灸"},
            {date: "02/08", onLunarCal: false, name: "こと始め"},
            {date: "02/08", onLunarCal: false, name: "針供養"},
            {date: "02/08", onLunarCal: true, name: "旧こと始め"},
            {date: "02/08", onLunarCal: true, name: "旧針供養"},
            {date: "02/11", onLunarCal: false, name: "紀元節"},
    
            {date: "02/01", onLunarCal: false, name: "プリキュアの日", since: 2004},
            {date: "02/01", onLunarCal: false, name: "テレビ放送記念日", since: 1953},
            {date: "02/02", onLunarCal: false, name: "ツインテールの日", since: 2012},
            {date: "02/02", onLunarCal: false, name: "情報セキュリティの日", since: 2006},
            {date: "02/03", onLunarCal: false, name: "のり巻きの日", since: 1987},
            {date: "02/03", onLunarCal: false, name: "大岡越前の日", since: null},
            {date: "02/03", onLunarCal: false, name: "にじさんじの日", since: 2019},
            {date: "02/04", onLunarCal: false, name: "ぷよの日", since: 2003},
            {date: "02/05", onLunarCal: false, name: "ピカチュウの日", since: 2011}, // Pixiv、Twitter最古の投稿年
            {date: "02/05", onLunarCal: false, name: "プロ野球の日", since: 1936},
            {date: "02/06", onLunarCal: false, name: "海苔の日", since: 1966},
            {date: "02/06", onLunarCal: false, name: "ブログの日", since: 2006},
            {date: "02/07", onLunarCal: false, name: "北方領土の日", since: 1981},
            {date: "02/07", onLunarCal: false, name: "フナの日", since: 2001},
            {date: "02/08", onLunarCal: false, name: "郵便マークの日", since: 1887},
            {date: "02/08", onLunarCal: false, name: "にわとりの日", since: 2017},
            {date: "02/09", onLunarCal: false, name: "漫画の日", since: 1990}, // 手塚治虫没年の翌年
            {date: "02/09", onLunarCal: false, name: "ふくの日", since: 1980},
            {date: "02/10", onLunarCal: false, name: "簿記の日", since: 2004},
            {date: "02/10", onLunarCal: false, name: "ニートの日", since: 2005}, // ニート流行りの頃
            {date: "02/10", onLunarCal: false, name: "ニットの日", since: 1994},
            {date: "02/11", onLunarCal: false, name: "わんこそば記念日", since: 1980},
            {date: "02/12", onLunarCal: false, name: "ボンカレーの日", since: 2007},
            {date: "02/12", onLunarCal: false, name: "ペニシリンの日", since: 1941}, // ペニシリン臨床実験成功年
            {date: "02/13", onLunarCal: false, name: "世界ラジオデー", since: 2012},
            {date: "02/13", onLunarCal: false, name: "苗字の日", since: 1875},
            {date: "02/14", onLunarCal: false, name: "聖バレンタインデー", since: 1958},
            {date: "02/14", onLunarCal: false, name: "煮干しの日", since: 2014},
            {date: "02/15", onLunarCal: false, name: "涅槃会", since: null},
            {date: "02/15", onLunarCal: false, name: "横手かまくら", since: null},
            {date: "02/16", onLunarCal: false, name: "天気図記念日", since: 1883},
            {date: "02/16", onLunarCal: false, name: "寒天の日", since: 2006},
            {date: "02/17", onLunarCal: false, name: "天使の囁きの日", since: 1994},
            {date: "02/17", onLunarCal: false, name: "中部国際空港開港記念日", since: 2005},
            {date: "02/17", onLunarCal: false, name: "ガチャの日", since: 2019},
            {date: "02/18", onLunarCal: false, name: "冥王星の日", since: 1930},
            {date: "02/18", onLunarCal: false, name: "エアメールの日", since: 1911},
            {date: "02/19", onLunarCal: false, name: "プロレスの日", since: 1954},
            {date: "02/19", onLunarCal: false, name: "チョコミントの日", since: 2021},
            {date: "02/20", onLunarCal: false, name: "普通選挙の日", since: 1928},
            {date: "02/20", onLunarCal: false, name: "歌舞伎の日", since: null},
            {date: "02/21", onLunarCal: false, name: "国際母語デー", since: 1999},
            {date: "02/21", onLunarCal: false, name: "漱石の日", since: 1911},
            {date: "02/22", onLunarCal: false, name: "猫の日", since: 1987},
            {date: "02/22", onLunarCal: false, name: "竹島の日", since: 2005},
            {date: "02/23", onLunarCal: false, name: "富士山の日", since: 1996},
            {date: "02/23", onLunarCal: false, name: "税理士記念日", since: 1969},
            {date: "02/24", onLunarCal: false, name: "鉄道ストの日", since: 1898},
            {date: "02/25", onLunarCal: false, name: "ヱビスの日", since: 2012},
            {date: "02/26", onLunarCal: false, name: "脱出の日", since: 1815},
            {date: "02/27", onLunarCal: false, name: "Pokémon Day", since: 2020},
            {date: "02/27", onLunarCal: false, name: "国際ホッキョクグマの日", since: 2005},
            {date: "02/28", onLunarCal: false, name: "ビスケットの日", since: 1980},
            {date: "02/29", onLunarCal: false, name: "にんにくの日", since: 2012},
            {date: "02/29", onLunarCal: false, name: "富士急の日", since: 2003},
        ],

        3: [
            {date: "03/03", onLunarCal: false, name: "ひな祭り"},
            {date: "03/03", onLunarCal: true, name: "旧ひな祭り"},
            {date: "03/16", onLunarCal: false, name: "十六団子"},
    
            {date: "03/01", onLunarCal: false, name: "ビキニ・デー", since: 1955},
            {date: "03/01", onLunarCal: false, name: "マヨネーズの日", since: 2015},
            {date: "03/02", onLunarCal: false, name: "ミニの日", since: 2001},
            {date: "03/03", onLunarCal: false, name: "耳の日", since: 1956},
            {date: "03/03", onLunarCal: false, name: "平和の日", since: 1985},
            {date: "03/04", onLunarCal: false, name: "バウムクーヘンの日", since: 2010},
            {date: "03/04", onLunarCal: false, name: "ミシンの日", since: 1991},
            {date: "03/05", onLunarCal: false, name: "珊瑚の日", since: 1996},
            {date: "03/06", onLunarCal: false, name: "弟の日", since: 1992},
            {date: "03/07", onLunarCal: false, name: "消防記念日", since: 1950},
            {date: "03/07", onLunarCal: false, name: "メンチカツの日", since: 2009},
            {date: "03/08", onLunarCal: false, name: "国際女性デー", since: 1975},
            {date: "03/08", onLunarCal: false, name: "エスカレーターの日", since: 1914},
            {date: "03/09", onLunarCal: false, name: "ミクの日", since: 2008},
            {date: "03/09", onLunarCal: false, name: "ザクの日", since: 2021},
            {date: "03/09", onLunarCal: false, name: "関門国道トンネル開通記念日", since: 1958},
            {date: "03/10", onLunarCal: false, name: "マリオの日", since: 2018},
            {date: "03/10", onLunarCal: false, name: "東海道・山陽新幹線<wbr>全通記念日", since: 1975},
            {date: "03/10", onLunarCal: false, name: "東京都平和の日", since: 1991},
            {date: "03/11", onLunarCal: false, name: "東日本大震災の日", since: 2012},
            {date: "03/12", onLunarCal: false, name: "スイーツの日", since: 2008},
            {date: "03/13", onLunarCal: false, name: "青函トンネル開業記念日", since: 1988},
            {date: "03/13", onLunarCal: false, name: "サンドイッチデー", since: 1892},
            {date: "03/14", onLunarCal: false, name: "ホワイトデー", since: 1980},
            {date: "03/14", onLunarCal: false, name: "円周率の日", since: null},
            {date: "03/15", onLunarCal: false, name: "靴の記念日", since: 1932},
            {date: "03/16", onLunarCal: false, name: "国立公園指定記念日", since: 1934},
            {date: "03/17", onLunarCal: false, name: "漫画週刊誌の日", since: 1959},
            {date: "03/18", onLunarCal: false, name: "点字ブロックの日", since: 2010},
            {date: "03/19", onLunarCal: false, name: "ミュージックの日", since: 1991},
            {date: "03/20", onLunarCal: false, name: "電卓の日", since: 1960},
            {date: "03/20", onLunarCal: false, name: "上野動物園開園記念日", since: 1882},
            {date: "03/21", onLunarCal: false, name: "ツイッター誕生日", since: 2006},
            {date: "03/21", onLunarCal: false, name: "ランドセルの日", since: 2005}, // Google検索最古のページ
            {date: "03/22", onLunarCal: false, name: "世界水の日", since: 1993},
            {date: "03/22", onLunarCal: false, name: "放送記念日", since: 1943},
            {date: "03/23", onLunarCal: false, name: "世界気象デー", since: 1960},
            {date: "03/23", onLunarCal: false, name: "スジャータの日", since: 2021},
            {date: "03/24", onLunarCal: false, name: "マネキン記念日", since: 1928},
            {date: "03/24", onLunarCal: false, name: "壇ノ浦の戦いの日", since: 1185},
            {date: "03/25", onLunarCal: false, name: "電気記念日", since: 1927},
            {date: "03/26", onLunarCal: false, name: "楽聖忌", since: 1827},
            {date: "03/27", onLunarCal: false, name: "さくらの日", since: 1992},
            {date: "03/28", onLunarCal: false, name: "三ツ矢サイダーの日", since: 2004},
            {date: "03/28", onLunarCal: false, name: "シルクロードの日", since: 1900},
            {date: "03/29", onLunarCal: false, name: "マリモ記念日", since: 1952},
            {date: "03/30", onLunarCal: false, name: "国立競技場落成記念日", since: 1958},
            {date: "03/31", onLunarCal: false, name: "オーケストラの日", since: 2007},
            {date: "03/31", onLunarCal: false, name: "山菜の日", since: 2012},
        ],
        4: [
            {date: "04/01", onLunarCal: false, name: "新学年", since: 1886},
            {date: "04/01", onLunarCal: false, name: "新財政年度", since: 1886},
            {date: "04/01", onLunarCal: false, name: "エイプリルフール", since: 1912}, // エイプリルフールの名称は大正時代から
            {date: "04/01", onLunarCal: false, name: "アップル創業", since: 1976, anniv: true},
            {date: "04/02", onLunarCal: false, name: "こどもの本の日", since: 1967},
            {date: "04/03", onLunarCal: false, name: "いんげん豆の日", since: 1673},
            {date: "04/03", onLunarCal: false, name: "シーサーの日", since: 2002},
            {date: "04/04", onLunarCal: false, name: "あんぱんの日", since: 2001},
            {date: "04/04", onLunarCal: false, name: "おかまの日", since: 1980}, // オカマが女性的な男性を指すようになったのが1980年代
            {date: "04/05", onLunarCal: false, name: "横丁の日", since: 2018},
            {date: "04/06", onLunarCal: false, name: "北極の日", since: 1909},
            {date: "04/06", onLunarCal: false, name: "コンビーフの日", since: 1950}, // 日本初の缶詰コンビーフ発売年
            {date: "04/07", onLunarCal: false, name: "世界保健デー", since: 1948},
            {date: "04/08", onLunarCal: false, name: "花祭り（潅仏会）", since: null},
            {date: "04/09", onLunarCal: false, name: "大仏開眼の日", since: 752},
            {date: "04/09", onLunarCal: false, name: "鍼灸の日", since: 2017},
            {date: "04/10", onLunarCal: false, name: "瀬戸大橋開通記念日", since: 1988},
            {date: "04/10", onLunarCal: false, name: "ショートカットの日", since: 2014},
            {date: "04/10", onLunarCal: false, name: "駅弁の日", since: 1993},
            {date: "04/11", onLunarCal: false, name: "メートル法公布記念日", since: 1921},
            {date: "04/11", onLunarCal: false, name: "中央線開業記念日", since: 1889},
            {date: "04/12", onLunarCal: false, name: "世界宇宙飛行の日", since: 2011},
            {date: "04/12", onLunarCal: false, name: "パンの記念日", since: 1983},
            {date: "04/13", onLunarCal: false, name: "喫茶店の日", since: 1888},
            {date: "04/14", onLunarCal: false, name: "ＳＯＳの日<br>（タイタニック号沈没の日）", since: 1912},
            {date: "04/14", onLunarCal: false, name: "オレンジデー", since: 2009},
            {date: "04/15", onLunarCal: false, name: "イリオモテヤマネコの日", since: 2016},
            {date: "04/15", onLunarCal: false, name: "ヘリコプターの日", since: 1986},
            {date: "04/16", onLunarCal: false, name: "チャップリンデー", since: 1940}, // 独裁者公開年
            {date: "04/16", onLunarCal: false, name: "えのすいの日", since: 2017},
            {date: "04/17", onLunarCal: false, name: "恐竜の日", since: 1923},
            {date: "04/17", onLunarCal: false, name: "なすび記念日", since: 2004},
            {date: "04/18", onLunarCal: false, name: "発明の日", since: 1954},
            {date: "04/18", onLunarCal: false, name: "アマチュア無線の日", since: 1973},
            {date: "04/19", onLunarCal: false, name: "地図の日", since: 1821}, // 伊能図完成年
            {date: "04/19", onLunarCal: false, name: "良いきゅうりの日", since: 2008},
            {date: "04/20", onLunarCal: false, name: "郵政記念日", since: 2001},
            {date: "04/20", onLunarCal: false, name: "ジャムの日", since: 2015},
            {date: "04/21", onLunarCal: false, name: "民放の日", since: 1993},
            {date: "04/21", onLunarCal: false, name: "ゲームボーイ", since: 1989, anniv: true},
            {date: "04/22", onLunarCal: false, name: "アースデー", since: 1970},
            {date: "04/22", onLunarCal: false, name: "バーバパパの日", since: 2020},
            {date: "04/23", onLunarCal: false, name: "子ども読書の日", since: 2002},
            {date: "04/23", onLunarCal: false, name: "地ビールの日", since: 2000},
            {date: "04/24", onLunarCal: false, name: "植物学の日", since: 1958},
            {date: "04/24", onLunarCal: false, name: "日本ダービー記念日", since: 1958},
            {date: "04/25", onLunarCal: false, name: "世界ペンギンの日", since: 1956}, // マクマード基地設立年
            {date: "04/26", onLunarCal: false, name: "海上自衛隊の日", since: 2013},
            {date: "04/26", onLunarCal: false, name: "よい風呂の日", since: 2012},
            {date: "04/27", onLunarCal: false, name: "星のカービィ", since: 1992, anniv: true},
            {date: "04/27", onLunarCal: false, name: "哲学の日", since: null},
            {date: "04/27", onLunarCal: false, name: "長崎港開港記念日", since: 1571},
            {date: "04/28", onLunarCal: false, name: "象の日", since: 1729},
            {date: "04/28", onLunarCal: false, name: "四葉の日", since: 2017},
            {date: "04/29", onLunarCal: false, name: "羊肉の日", since: 2004},
            {date: "04/30", onLunarCal: false, name: "図書館記念日", since: 1972},
            {date: "04/30", onLunarCal: false, name: "ヴァルプルギスの夜", since: null},
    
        ],
        5: [
            {date: "05/05", onLunarCal: false, name: "端午の節句"},
            {date: "05/05", onLunarCal: true, name: "旧端午の節句"},

            {date: "05/01", onLunarCal: false, name: "メーデー", since: 1890},
            {date: "05/01", onLunarCal: false, name: "令和改元の日", since: 2019},
            {date: "05/02", onLunarCal: false, name: "郵便貯金の日", since: 1950},
            {date: "05/03", onLunarCal: false, name: "リカちゃんの誕生日", since: 1968},
            {date: "05/04", onLunarCal: false, name: "ラムネの日", since: 1872},
            {date: "05/04", onLunarCal: false, name: "スターウォーズデー", since: 1977},
            {date: "05/05", onLunarCal: false, name: "手話記念日", since: 2003},
            {date: "05/05", onLunarCal: false, name: "薬の日", since: 1987},
            {date: "05/06", onLunarCal: false, name: "ゴムの日", since: 1900}, // 不明　ゴム製造拡大前後
            {date: "05/07", onLunarCal: false, name: "世界エイズ孤児デー", since: 2002},
            {date: "05/08", onLunarCal: false, name: "世界赤十字デー", since: 1948},
            {date: "05/08", onLunarCal: false, name: "ゴーヤーの日", since: 1997},
            {date: "05/09", onLunarCal: false, name: "アイスクリームの日", since: 1965},
            {date: "05/09", onLunarCal: false, name: "悟空の日・ピッコロの日", since: 1984}, // とりあえず週刊誌連載開始時
            {date: "05/10", onLunarCal: false, name: "愛鳥週間", since: 1950},
            {date: "05/10", onLunarCal: false, name: "メイドの日", since: 1990}, // 属性として認知されてきた頃
            {date: "05/11", onLunarCal: false, name: "長良川鵜飼開き", since: null},
            {date: "05/12", onLunarCal: false, name: "看護の日", since: 1991},
            {date: "05/12", onLunarCal: false, name: "海上保安の日", since: 2000},
            {date: "05/13", onLunarCal: false, name: "愛犬の日", since: 1956},
            {date: "05/13", onLunarCal: false, name: "カクテルの日", since: 1806},
            {date: "05/14", onLunarCal: false, name: "温度計の日", since: null},
            {date: "05/15", onLunarCal: false, name: "沖縄本土復帰記念日", since: 1972},
            {date: "05/15", onLunarCal: false, name: "ストッキングの日", since: 1940},
            {date: "05/16", onLunarCal: false, name: "旅の日", since: 1988},
            {date: "05/17", onLunarCal: false, name: "国際反ホモフォビアの日", since: 2005},
            {date: "05/17", onLunarCal: false, name: "お茶漬けの日", since: 2012},
            {date: "05/18", onLunarCal: false, name: "国際博物館の日", since: 1978},
            {date: "05/18", onLunarCal: false, name: "ファイバーの日", since: 2005},
            {date: "05/19", onLunarCal: false, name: "ボクシングの日", since: 2010},
            {date: "05/19", onLunarCal: false, name: "セメントの日", since: 1875},
            {date: "05/20", onLunarCal: false, name: "東京港開港記念日", since: 1941},
            {date: "05/20", onLunarCal: false, name: "成田国際空港開港記念日", since: 1978},
            {date: "05/21", onLunarCal: false, name: "小学校開校の日", since: 1869},
            {date: "05/22", onLunarCal: false, name: "サイクリングの日", since: 2009},
            {date: "05/23", onLunarCal: false, name: "キスの日", since: 1946},
            {date: "05/24", onLunarCal: false, name: "伊達巻の日", since: 1948}, // 制定した会社の創業年
            {date: "05/25", onLunarCal: false, name: "広辞苑記念日", since: 1955},
            {date: "05/25", onLunarCal: false, name: "主婦休みの日", since: 2009},
            {date: "05/26", onLunarCal: false, name: "東名高速道路全通記念日", since: 1969},
            {date: "05/26", onLunarCal: false, name: "ル・マンの日", since: 1923},
            {date: "05/27", onLunarCal: false, name: "ドラゴンクエスト", since: 1986, anniv: true},
            {date: "05/27", onLunarCal: false, name: "百人一首の日", since: null},
            {date: "05/28", onLunarCal: false, name: "ゴルフ記念日", since: 1994},
            {date: "05/29", onLunarCal: false, name: "エベレスト登頂記念日", since: 1953},
            {date: "05/29", onLunarCal: false, name: "こんにゃくの日", since: 1989},
            {date: "05/30", onLunarCal: false, name: "掃除機の日", since: 1997},
            {date: "05/30", onLunarCal: false, name: "２ちゃんねる開設の日", since: 1999},
            {date: "05/31", onLunarCal: false, name: "世界禁煙デー", since: 1989},
        ],
        6: [
            {date: "06/01", onLunarCal: false, name: "気象記念日", since: 1884},
            {date: "06/01", onLunarCal: false, name: "電波の日", since: 1951},
            {date: "06/01", onLunarCal: false, name: "写真の日", since: 1951},
            {date: "06/02", onLunarCal: false, name: "横浜港開港記念日", since: 1859},
            {date: "06/03", onLunarCal: false, name: "測量の日", since: 1989},
            {date: "06/03", onLunarCal: false, name: "雲仙普賢岳祈りの日", since: 1998},
            {date: "06/04", onLunarCal: false, name: "虫の日", since: 1988},
            {date: "06/04", onLunarCal: false, name: "ムシキングの日", since: 2016},
            {date: "06/05", onLunarCal: false, name: "環境の日", since: 1973},
            {date: "06/06", onLunarCal: false, name: "楽器の日", since: 1970},
            {date: "06/06", onLunarCal: false, name: "ロールケーキの日", since: 2005},
            {date: "06/07", onLunarCal: false, name: "緑内障を考える日", since: 2005},
            {date: "06/w1-1", onLunarCal: false, name: "寄席の日", since: 1973},
            {date: "06/08", onLunarCal: false, name: "世界海洋デー", since: 2009},
            {date: "06/09", onLunarCal: false, name: "ロックの日", since: 1955}, // 日本で最初のロックンロール・レコードが発売された年 by ウィキペ
            {date: "06/10", onLunarCal: false, name: "時の記念日", since: 1920},
            {date: "06/10", onLunarCal: false, name: "ミルクキャラメルの日", since: 2000},
            {date: "06/11", onLunarCal: false, name: "傘の日", since: 1989},
            {date: "06/11", onLunarCal: false, name: "カメハメハ・デー", since: 1810},
            {date: "06/12", onLunarCal: false, name: "エスペラントの日", since: 1906},
            {date: "06/13", onLunarCal: false, name: "はやぶさの日", since: 2010},
            {date: "06/13", onLunarCal: false, name: "鉄人の日", since: 1987},
            {date: "06/14", onLunarCal: false, name: "世界献血デー", since: 2004},
            {date: "06/14", onLunarCal: false, name: "手羽先記念日", since: 1981},
            {date: "06/15", onLunarCal: false, name: "生姜の日", since: 2009},
            {date: "06/16", onLunarCal: false, name: "スペースインベーダーの日", since: 2018},
            {date: "06/16", onLunarCal: false, name: "和菓子の日", since: 1979},
            {date: "06/17", onLunarCal: false, name: "薩摩の日", since: 1866}, // 英国公使パークスが薩摩藩を訪問した年
            {date: "06/18", onLunarCal: false, name: "おにぎりの日", since: 2002},
            {date: "06/18", onLunarCal: false, name: "国際寿司の日", since: 2009},
            {date: "06/19", onLunarCal: false, name: "太宰治生誕祭", since: 1999},
            {date: "06/19", onLunarCal: false, name: "理化学研究所創設の日", since: 1917},
            {date: "06/20", onLunarCal: false, name: "世界難民の日", since: 2000},
            {date: "06/20", onLunarCal: false, name: "ペパーミントの日", since: 1987},
            {date: "06/w3-0", onLunarCal: false, name: "父の日", since: 1910},
            {date: "06/21", onLunarCal: false, name: "スナックの日", since: 1985}, // 全日本菓子協会設立年
            {date: "06/21", onLunarCal: false, name: "冷蔵庫の日", since: 1985},
            {date: "06/22", onLunarCal: false, name: "ボウリングの日", since: 1972},
            {date: "06/22", onLunarCal: false, name: "かにの日", since: 1999},
            {date: "06/23", onLunarCal: false, name: "沖縄慰霊の日", since: 1961},
            {date: "06/23", onLunarCal: false, name: "オリンピックデー", since: 1948},
            {date: "06/23", onLunarCal: false, name: "ニンテンドウ６４", since: 1996, anniv: true},
            {date: "06/24", onLunarCal: false, name: "ＵＦＯ記念日", since: 1947},
            {date: "06/24", onLunarCal: false, name: "ドレミの日", since: 1024},
            {date: "06/25", onLunarCal: false, name: "サザンの日", since: 1978},
            {date: "06/25", onLunarCal: false, name: "百合の日", since: 2019},
            {date: "06/25", onLunarCal: false, name: "住宅デー", since: 1978},
            {date: "06/26", onLunarCal: false, name: "ＧＵＭＩ記念日", since: 2009},
            {date: "06/26", onLunarCal: false, name: "露天風呂の日", since: 1987},
            {date: "06/27", onLunarCal: false, name: "ちらし寿司の日", since: 2011},
            {date: "06/27", onLunarCal: false, name: "演説の日", since: 1874},
            {date: "06/28", onLunarCal: false, name: "貿易の日", since: 1963},
            {date: "06/28", onLunarCal: false, name: "パフェの日", since: 1950},
            {date: "06/29", onLunarCal: false, name: "星の王子さまの日", since: 1999},
            {date: "06/29", onLunarCal: false, name: "ｉＰｈｏｎｅ", since: 2007, anniv: true},
            {date: "06/30", onLunarCal: false, name: "トランジスタの日", since: 1948},
            {date: "06/30", onLunarCal: false, name: "アインシュタイン記念日", since: 1905},
    
        ],
        7: [
            {date: "07/07", onLunarCal: false, name: "七夕"},
            {date: "07/07", onLunarCal: true, name: "旧七夕"},
            {date: "07/13", onLunarCal: false, name: "ぼん迎え火"},
            {date: "07/15", onLunarCal: false, name: "ぼん・中元"},
            {date: "07/15", onLunarCal: true, name: "旧ぼん"},
            {date: "07/16", onLunarCal: false, name: "閻魔詣り・ぼん送り火"},
            {date: "07/24", onLunarCal: false, name: "地蔵ぼん"},
    
            {date: "07/01", onLunarCal: false, name: "富士山山開き", since: null},
            {date: "07/01", onLunarCal: false, name: "国民安全の日", since: 1960},
            {date: "07/02", onLunarCal: false, name: "うどんの日", since: 1980},
            {date: "07/02", onLunarCal: false, name: "たわしの日", since: 1915},
            {date: "07/03", onLunarCal: false, name: "通天閣の日", since: 1912},
            {date: "07/03", onLunarCal: false, name: "ソフトクリームの日", since: 1990},
            {date: "07/04", onLunarCal: false, name: "米国独立記念日", since: 1776},
            {date: "07/04", onLunarCal: false, name: "梨の日", since: 2004},
            {date: "07/05", onLunarCal: false, name: "穴子の日", since: 1992}, // 制定者がグリーンフーズに社名変更時点
            {date: "07/05", onLunarCal: false, name: "江戸切子の日", since: 2004},
            {date: "07/06", onLunarCal: false, name: "サラダ記念日", since: 1987},
            {date: "07/06", onLunarCal: false, name: "ピアノの日", since: 1823},
            {date: "07/06", onLunarCal: false, name: "零戦の日", since: 1939},
            {date: "07/07", onLunarCal: false, name: "そうめんの日", since: 1982},
            {date: "07/07", onLunarCal: false, name: "カルピスの日", since: 2009},
            {date: "07/08", onLunarCal: false, name: "ガンダムの日", since: 1979}, // 1stガンダム放映年
            {date: "07/09", onLunarCal: false, name: "ジェットコースターの日", since: 1955},
            {date: "07/10", onLunarCal: false, name: "ウルトラマンの日", since: 1966},
            {date: "07/10", onLunarCal: false, name: "納豆の日", since: 1981},
            {date: "07/11", onLunarCal: false, name: "真珠記念日", since: 1893},
            {date: "07/11", onLunarCal: false, name: "ラーメンの日", since: 2017},
            {date: "07/11", onLunarCal: false, name: "ＹＳ―１１記念日", since: 1962},
            {date: "07/12", onLunarCal: false, name: "ラジオ本放送の日", since: 1925},
            {date: "07/13", onLunarCal: false, name: "日本標準時制定記念日", since: 1888},
            {date: "07/13", onLunarCal: false, name: "オカルト記念日", since: 1974},
            {date: "07/14", onLunarCal: false, name: "衛星ひまわりの日", since: 1977},
            {date: "07/14", onLunarCal: false, name: "ペリー上陸記念日", since: 1853},
            {date: "07/14", onLunarCal: false, name: "ゼリーの日", since: 2005},
            {date: "07/15", onLunarCal: false, name: "大阪港開港記念日", since: 1868},
            {date: "07/15", onLunarCal: false, name: "ホッピーの日", since: 1948},
            {date: "07/15", onLunarCal: false, name: "ファミコン", since: 1983, anniv: true},
            {date: "07/16", onLunarCal: false, name: "駅弁記念日", since: 2001},
            {date: "07/16", onLunarCal: false, name: "虹の日", since: 2008},
            {date: "07/17", onLunarCal: false, name: "漫画の日", since: 1862}, // ジャパン・パンチの発刊年
            {date: "07/18", onLunarCal: false, name: "光化学スモッグの日", since: 1970},
            {date: "07/19", onLunarCal: false, name: "サイボーグ００９の日", since: 2008},
            {date: "07/20", onLunarCal: false, name: "月面着陸の日", since: 1969},
            {date: "07/21", onLunarCal: false, name: "自然公園の日", since: 1957},
            {date: "07/22", onLunarCal: false, name: "著作権制度の日", since: 1899},
            {date: "07/23", onLunarCal: false, name: "ふみの日", since: 1979},
            {date: "07/23", onLunarCal: false, name: "米騒動の日", since: 1918},
            {date: "07/24", onLunarCal: false, name: "テレワーク・デイ", since: 2017},
            {date: "07/25", onLunarCal: false, name: "大阪天満宮天神祭", since: null},
            {date: "07/25", onLunarCal: false, name: "かき氷の日"}, // 1933年の日本最高気温更新の翌年に仮置き
            {date: "07/26", onLunarCal: false, name: "アイドルマスター", since: 2005, anniv: true},
            {date: "07/26", onLunarCal: false, name: "幽霊の日", since: 1825},
            {date: "07/27", onLunarCal: false, name: "スイカの日", since: null},
            {date: "07/28", onLunarCal: false, name: "地図の日", since: 2008},
            {date: "07/28", onLunarCal: false, name: "なにわの日", since: 2007},
            {date: "07/29", onLunarCal: false, name: "アマチュア無線の日", since: 1952},
            {date: "07/29", onLunarCal: false, name: "福神漬の日", since: 2010},
            {date: "07/30", onLunarCal: false, name: "プロレス記念日", since: 1953},
            {date: "07/30", onLunarCal: false, name: "梅干の日", since: 2004},
            {date: "07/31", onLunarCal: false, name: "ＧＬＡＹの日", since: 1999},
        ],
        8: [
            {date: "08/01", onLunarCal: false, name: "八朔"},
            {date: "08/01", onLunarCal: true, name: "旧八朔"},
            {date: "08/02", onLunarCal: true, name: "二日灸"},
            {date: "08/15", onLunarCal: false, name: "月遅れぼん"},
            {date: "08/15", onLunarCal: true, name: "十五夜"},
            {date: "08/24", onLunarCal: false, name: "月遅れ地蔵盆"},
    
            {date: "08/01", onLunarCal: false, name: "水の日", since: 1977},
            {date: "08/01", onLunarCal: false, name: "花火の日", since: 1967},
            {date: "08/02", onLunarCal: false, name: "おやつの日", since: 2015},
            {date: "08/02", onLunarCal: false, name: "カレーうどんの日", since: 2010},
            {date: "08/03", onLunarCal: false, name: "はちみつの日", since: 1985},
            {date: "08/03", onLunarCal: false, name: "はもの日", since: 2021},
            {date: "08/04", onLunarCal: false, name: "箸の日", since: 1975},
            {date: "08/04", onLunarCal: false, name: "橋の日", since: 1986},
            {date: "08/05", onLunarCal: false, name: "パピコの日", since: 2019},
            {date: "08/05", onLunarCal: false, name: "タクシーの日", since: 1984},
            {date: "08/05", onLunarCal: false, name: "ハードコアの日", since: 2006},
            {date: "08/06", onLunarCal: false, name: "広島原爆の日", since: 1945},
            {date: "08/07", onLunarCal: false, name: "バナナの日", since: 2001},
            {date: "08/07", onLunarCal: false, name: "鼻の日", since: 1961},
            {date: "08/08", onLunarCal: false, name: "そろばんの日", since: 1968},
            {date: "08/08", onLunarCal: false, name: "プチプチの日", since: 2000},
            {date: "08/09", onLunarCal: false, name: "長崎原爆の日", since: 1945},
            {date: "08/09", onLunarCal: false, name: "ムーミンの日", since: 2005},
            {date: "08/09", onLunarCal: false, name: "野球の日", since: 1989}, // エスポートミズノ開店年
            {date: "08/10", onLunarCal: false, name: "道の日", since: 1986},
            {date: "08/10", onLunarCal: false, name: "ハーゲンダッツの日", since: 2017},
            {date: "08/10", onLunarCal: false, name: "野獣の日", since: 2012}, // ニコ百科記事作成年
            {date: "08/11", onLunarCal: false, name: "きのこの山の日", since: 2016}, // ニコ百科記事作成年
            {date: "08/12", onLunarCal: false, name: "航空安全の日", since: 1986}, // JAL123便事故翌年
            {date: "08/12", onLunarCal: false, name: "ハイチュウの日", since: 2004},
            {date: "08/13", onLunarCal: false, name: "左利きの日", since: 1990},
            {date: "08/14", onLunarCal: false, name: "水泳の日", since: 2014},
            {date: "08/15", onLunarCal: false, name: "終戦記念日", since: 1945},
            {date: "08/16", onLunarCal: false, name: "月遅れぼん送り火", since: 1945},
            {date: "08/17", onLunarCal: false, name: "パイナップルの日"},
            {date: "08/18", onLunarCal: false, name: "高校野球記念日", since: 1915},
            {date: "08/18", onLunarCal: false, name: "米の日", since: 1978},
            {date: "08/19", onLunarCal: false, name: "俳句の日", since: 1991},
            {date: "08/19", onLunarCal: false, name: "バイクの日", since: 1989},
            {date: "08/20", onLunarCal: false, name: "蚊の日", since: 1930},
            {date: "08/20", onLunarCal: false, name: "Ｙａｈｏｏ！の日", since: 1996}, // Yahoo!開設年
            {date: "08/21", onLunarCal: false, name: "女子大生の日", since: 2020},
            {date: "08/21", onLunarCal: false, name: "献血の日", since: 1964},
            {date: "08/22", onLunarCal: false, name: "チンチン電車の日", since: 1904},
            {date: "08/23", onLunarCal: false, name: "白虎隊自刃の日", since: 1904},
            {date: "08/23", onLunarCal: false, name: "油の日", since: 2013},
            {date: "08/24", onLunarCal: false, name: "ウクライナ独立記念日", since: 1991},
            {date: "08/24", onLunarCal: false, name: "愛酒の日", since: 1928}, // 若山牧水没年
            {date: "08/25", onLunarCal: false, name: "即席ラーメン記念日", since: 1958}, // チキンラーメン発売年
            {date: "08/25", onLunarCal: false, name: "東京国際空港開港記念日", since: 1931},
            {date: "08/25", onLunarCal: false, name: "リナックス", since: 1991, anniv: true},
            {date: "08/26", onLunarCal: false, name: "レインボーブリッジ<wbr>開通記念日", since: 1993},
            {date: "08/26", onLunarCal: false, name: "パワプロの日", since: 2016},
            {date: "08/27", onLunarCal: false, name: "男はつらいよの日", since: 1969},
            {date: "08/28", onLunarCal: false, name: "テレビＣＭの日", since: 2005},
            {date: "08/28", onLunarCal: false, name: "天気予報士の日", since: 1994},
            {date: "08/29", onLunarCal: false, name: "焼き肉の日", since: 1993},
            {date: "08/29", onLunarCal: false, name: "ケーブルカーの日", since: 1918},
            {date: "08/30", onLunarCal: false, name: "国際失踪者デー", since: 2006},
            {date: "08/30", onLunarCal: false, name: "ハッピーサンシャインデー", since: 2006}, // Google検索の最古ページ
            {date: "08/31", onLunarCal: false, name: "初音ミク記念日", since: 2008},
            {date: "08/31", onLunarCal: false, name: "野菜の日", since: 1983},
    
        ],
        9: [
            {date: "09/09", onLunarCal: false, name: "重陽"},
            {date: "09/09", onLunarCal: true, name: "旧重陽"},
            {date: "09/13", onLunarCal: true, name: "十三夜"},
    
            {date: "09/01", onLunarCal: false, name: "関東大震災の日", since: 1923},
            {date: "09/01", onLunarCal: false, name: "防災の日", since: 1960},
            {date: "09/02", onLunarCal: false, name: "宝くじの日", since: 1967},
            {date: "09/02", onLunarCal: false, name: "くず餅の日", since: 2021},
            {date: "09/03", onLunarCal: false, name: "ドラえもん誕生日", since: 1969},
            {date: "09/03", onLunarCal: false, name: "ホームラン記念日", since: 1977},
            {date: "09/04", onLunarCal: false, name: "関西国際空港開港記念日", since: 1994},
            {date: "09/04", onLunarCal: false, name: "櫛（くし）の日", since: 1978},
            {date: "09/04", onLunarCal: false, name: "串カツの日", since: 2020},
            {date: "09/05", onLunarCal: false, name: "石炭の日", since: 1992},
            {date: "09/06", onLunarCal: false, name: "松崎しげるの日", since: 2015},
            {date: "09/06", onLunarCal: false, name: "黒の日", since: 1989},
            {date: "09/06", onLunarCal: false, name: "妹の日", since: 1991},
            {date: "09/07", onLunarCal: false, name: "ＣＭソングの日", since: 1951},
            {date: "09/08", onLunarCal: false, name: "サンフランシスコ<wbr>平和条約調印記念日", since: 1951},
            {date: "09/08", onLunarCal: false, name: "ハヤシの日", since: 2016},
            {date: "09/09", onLunarCal: false, name: "救急の日", since: 1982},
            {date: "09/09", onLunarCal: false, name: "世界占いの日", since: 1999},
            {date: "09/09", onLunarCal: false, name: "チョロＱの日", since: 1980},
            {date: "09/10", onLunarCal: false, name: "苦汁（にがり）の日", since: 2018},
            {date: "09/10", onLunarCal: false, name: "屋外広告の日", since: 1974},
            {date: "09/11", onLunarCal: false, name: "公衆電話の日", since: 1900},
            {date: "09/11", onLunarCal: false, name: "たんぱく質の日", since: 2021},
            {date: "09/12", onLunarCal: false, name: "宇宙の日", since: 1992},
            {date: "09/12", onLunarCal: false, name: "水路記念日", since: 1971},
            {date: "09/12", onLunarCal: false, name: "マラソンの日", since: 1896}, // 最初のオリンピック開催年
            {date: "09/13", onLunarCal: false, name: "世界法の日", since: 1965},
            {date: "09/13", onLunarCal: false, name: "北斗の拳の日", since: 2018},
            {date: "09/13", onLunarCal: false, name: "スーパーマリオ", since: 1985},
            {date: "09/14", onLunarCal: false, name: "コスモスの日", since: 1980}, // バレンタインデーが定着した頃
            {date: "09/14", onLunarCal: false, name: "ゲームキューブ", since: 2001, anniv: true},
            {date: "09/15", onLunarCal: false, name: "老人の日", since: 2003},
            {date: "09/15", onLunarCal: false, name: "国際民主主義デー", since: 2007},
            {date: "09/16", onLunarCal: false, name: "国際オゾン層保護デー", since: 1994},
            {date: "09/16", onLunarCal: false, name: "マッチの日", since: 1948},
            {date: "09/17", onLunarCal: false, name: "モノレール開業記念日", since: 1964},
            {date: "09/17", onLunarCal: false, name: "イタリア料理の日", since: 2010},
            {date: "09/18", onLunarCal: false, name: "かいわれ大根の日", since: 1987},
            {date: "09/18", onLunarCal: false, name: "しまくとぅばの日", since: 2006},
            {date: "09/19", onLunarCal: false, name: "苗字の日", since: 1870},
            {date: "09/19", onLunarCal: false, name: "九十九島の日", since: 1999},
            {date: "09/20", onLunarCal: false, name: "空の日", since: 1992},
            {date: "09/20", onLunarCal: false, name: "国産ロケット<wbr>初打ち上げの日", since: 1957},
            {date: "09/20", onLunarCal: false, name: "バスの日", since: 1987},
            {date: "09/20", onLunarCal: false, name: "動物愛護週間", since: 1954},
            {date: "09/21", onLunarCal: false, name: "国際平和デー", since: 1981},
            {date: "09/21", onLunarCal: false, name: "ファッションショーの日", since: 1927},
            {date: "09/22", onLunarCal: false, name: "ワン・ウェブ・デー", since: 2006},
            {date: "09/22", onLunarCal: false, name: "フィットネスの日", since: 2014},
            {date: "09/23", onLunarCal: false, name: "海王星の日", since: 1846},
            {date: "09/23", onLunarCal: false, name: "不動産の日", since: 1984},
            {date: "09/24", onLunarCal: false, name: "世界ゴリラの日", since: 2017},
            {date: "09/24", onLunarCal: false, name: "畳の日", since: 1997},
            {date: "09/24", onLunarCal: false, name: "結核予防週間", since: 1962},
            {date: "09/25", onLunarCal: false, name: "骨董の日", since: 2017},
            {date: "09/25", onLunarCal: false, name: "スターリングシルバーの日", since: 2019},
            {date: "09/25", onLunarCal: false, name: "主婦休みの日", since: 2009},
            {date: "09/26", onLunarCal: false, name: "台風襲来の日", since: 1954}, // 洞爺丸台風襲来年
            {date: "09/26", onLunarCal: false, name: "ワープロ記念日", since: 1978},
            {date: "09/27", onLunarCal: false, name: "グーグル創立記念日", since: 2006},
            {date: "09/27", onLunarCal: false, name: "女性ドライバーの日", since: 1917},
            {date: "09/28", onLunarCal: false, name: "パソコン記念日", since: 1979}, // PC-8001発売年
            {date: "09/29", onLunarCal: false, name: "クリーニングの日", since: 1982},
            {date: "09/29", onLunarCal: false, name: "招き猫の日", since: 1995},
            {date: "09/30", onLunarCal: false, name: "クレーンの日", since: 1980},
            {date: "09/30", onLunarCal: false, name: "くるみの日", since: 2000}, // 日本くるみ会議による新クルミ栽培の手引き刊行年
    
        ],
        10: [
            {date: "10/10", onLunarCal: true, name: "とおかんや"},
            {date: "10/15", onLunarCal: true, name: "下元"},
            {date: "10/20", onLunarCal: true, name: "旧えびす講"},
            {date: "10/20", onLunarCal: true, name: "旧誓文払い"},

            {date: "10/01", onLunarCal: false, name: "法の日", since: 1960},
            {date: "10/01", onLunarCal: false, name: "日本酒の日", since: 1978},
            {date: "10/01", onLunarCal: false, name: "コーヒーの日", since: 1983},
            {date: "10/01", onLunarCal: false, name: "天下一品の日", since: 1999},
            {date: "10/01", onLunarCal: false, name: "東海道新幹線開業記念日", since: 1964},
            {date: "10/02", onLunarCal: false, name: "豆腐の日", since: 1993},
            {date: "10/02", onLunarCal: false, name: "東武の日", since: 2005},
            {date: "10/02", onLunarCal: false, name: "関越自動車道全通記念日", since: 1985},
            {date: "10/03", onLunarCal: false, name: "登山の日", since: 1992},
            {date: "10/03", onLunarCal: false, name: "ドイツ統一の日", since: 1990},
            {date: "10/03", onLunarCal: false, name: "アンパンマンの日", since: 2016},
            {date: "10/04", onLunarCal: false, name: "イワシの日", since: 1985},
            {date: "10/04", onLunarCal: false, name: "ロールキャベツの日", since: 2020},
            {date: "10/05", onLunarCal: false, name: "時刻表記念日", since: 2011}, // 手塚猛昌顕彰之碑建立年
            {date: "10/05", onLunarCal: false, name: "レモンの日", since: 1956}, // 高村光太郎没年
            {date: "10/06", onLunarCal: false, name: "国際協力の日", since: 1987},
            {date: "10/06", onLunarCal: false, name: "役所改革の日", since: 1969},
            {date: "10/07", onLunarCal: false, name: "盗難防止の日", since: 2003},
            {date: "10/07", onLunarCal: false, name: "ミステリー記念日", since: 1963}, // ポオ全集刊行年
            {date: "10/07", onLunarCal: false, name: "バーコードの日", since: 1952}, // 特許取得年
            {date: "10/w1-0", onLunarCal: false, name: "シャツの日", since: 1979},
            {date: "10/08", onLunarCal: false, name: "木の日", since: 1977},
            {date: "10/08", onLunarCal: false, name: "焼きおにぎりの日", since: 2015},
            {date: "10/09", onLunarCal: false, name: "世界郵便デー", since: 1984},
            {date: "10/09", onLunarCal: false, name: "トラックの日", since: 1992},
            {date: "10/09", onLunarCal: false, name: "トクホの日", since: 2010},
            {date: "10/10", onLunarCal: false, name: "デジタルの日", since: 2015},
            {date: "10/10", onLunarCal: false, name: "萌の日", since: 2015},
            {date: "10/10", onLunarCal: false, name: "お好み焼きの日", since: 2006},
            {date: "10/10", onLunarCal: false, name: "目の愛護デー", since: 1947},
            {date: "10/10", onLunarCal: false, name: "銭湯の日", since: 1991},
            {date: "10/10", onLunarCal: false, name: "ちくわぶの日", since: 2018},
            {date: "10/11", onLunarCal: false, name: "デジタルの日", since: 2015},
            {date: "10/11", onLunarCal: false, name: "ウィンクの日", since: 2000}, // ググった感じ2000年以降
            {date: "10/12", onLunarCal: false, name: "豆乳の日", since: 2008},
            {date: "10/12", onLunarCal: false, name: "コロンブス・デー", since: 1866},
            {date: "10/13", onLunarCal: false, name: "サツマイモの日", since: 1987},
            {date: "10/13", onLunarCal: false, name: "豆の日", since: 2010},
            {date: "10/13", onLunarCal: false, name: "引越しの日", since: 1989},
            {date: "10/14", onLunarCal: false, name: "鉄道の日", since: 1922},
            {date: "10/14", onLunarCal: false, name: "焼うどんの日", since: 1922},
            {date: "10/w2-1", onLunarCal: false, name: "鯛の日", since: 2006},
            {date: "10/15", onLunarCal: false, name: "世界手洗いの日", since: 2008},
            {date: "10/15", onLunarCal: false, name: "きのこの日", since: 1995},
            {date: "10/16", onLunarCal: false, name: "世界食料デー", since: 1981},
            {date: "10/17", onLunarCal: false, name: "沖縄そばの日", since: 1978},
            {date: "10/17", onLunarCal: false, name: "貯蓄の日", since: 1952},
            {date: "10/18", onLunarCal: false, name: "統計の日", since: 1973},
            {date: "10/18", onLunarCal: false, name: "冷凍食品の日", since: 1986},
            {date: "10/19", onLunarCal: false, name: "世界旅行の日", since: 1964}, // 海外旅行自由化の年
            {date: "10/19", onLunarCal: false, name: "ＴＯＥＩＣの日", since: 2021},
            {date: "10/20", onLunarCal: false, name: "えびす講", since: null},
            {date: "10/20", onLunarCal: false, name: "誓文払い", since: null},
            {date: "10/20", onLunarCal: false, name: "リサイクルの日", since: 1990},
            {date: "10/20", onLunarCal: false, name: "シチューライスの日", since: 2019},
            {date: "10/21", onLunarCal: false, name: "国際反戦デー", since: 1966},
            {date: "10/21", onLunarCal: false, name: "あかりの日", since: 1981},
            {date: "10/w3-0", onLunarCal: false, name: "まごの日", since: 1999},
            {date: "10/22", onLunarCal: false, name: "平安遷都の日", since: null},
            {date: "10/22", onLunarCal: false, name: "京都平安神宮時代祭", since: 1895},
            {date: "10/22", onLunarCal: false, name: "アニメの日", since: 2017},
            {date: "10/23", onLunarCal: false, name: "電信電話記念日", since: 1950},
            {date: "10/23", onLunarCal: false, name: "モルの日", since: 1980},
            {date: "10/23", onLunarCal: false, name: "じゃがりこの日", since: 1995},
            {date: "10/24", onLunarCal: false, name: "暗黒の木曜日", since: 1929},
            {date: "10/24", onLunarCal: false, name: "マーガリンの日", since: 2016},
            {date: "10/25", onLunarCal: false, name: "世界パスタデー", since: 1998},
            {date: "10/25", onLunarCal: false, name: "新潟米の日", since: 2010},
            {date: "10/26", onLunarCal: false, name: "原子力デー", since: 1964},
            {date: "10/26", onLunarCal: false, name: "柿の日", since: 2005},
            {date: "10/26", onLunarCal: false, name: "きしめんの日", since: 2008},
            {date: "10/27", onLunarCal: false, name: "読書の日", since: 1997},
            {date: "10/27", onLunarCal: false, name: "テディベアズ・デー", since: 1997},
            {date: "10/27", onLunarCal: false, name: "世界新記録の日", since: 1931},
            {date: "10/28", onLunarCal: false, name: "速記の日", since: 1888},
            {date: "10/28", onLunarCal: false, name: "おだしの日", since: 2016},
            {date: "10/28", onLunarCal: false, name: "豆花記念日", since: 2018},
            {date: "10/29", onLunarCal: false, name: "インターネット誕生日", since: 1969},
            {date: "10/29", onLunarCal: false, name: "ドリアの日", since: 2021},
            {date: "10/29", onLunarCal: false, name: "メガドライブ", since: 1988, anniv: true},
            {date: "10/30", onLunarCal: false, name: "たまごかけごはんの日", since: 2005},
            {date: "10/30", onLunarCal: false, name: "初恋の日", since: 1896},
            {date: "10/31", onLunarCal: false, name: "ハロウィン", since: 1995}, // 1990年代後半に始まったTDLイベントより
            {date: "10/31", onLunarCal: false, name: "日本茶の日", since: 2002},
        ],
        11: [
            {date: "11/15", onLunarCal: false, name: "七五三", since: null},

            {date: "11/01", onLunarCal: false, name: "計量記念日", since: 1952},
            {date: "11/01", onLunarCal: false, name: "自衛隊記念日", since: 1966},
            {date: "11/01", onLunarCal: false, name: "すしの日", since: 1961},
            {date: "11/01", onLunarCal: false, name: "紅茶の日", since: 1983},
            {date: "11/02", onLunarCal: false, name: "タイツの日", since: 2009},
            {date: "11/02", onLunarCal: false, name: "阪神タイガース記念日", since: 1985},
            {date: "11/03", onLunarCal: false, name: "まんがの日", since: 2002},
            {date: "11/03", onLunarCal: false, name: "ちゃんぽん麺の日", since: 1988},
            {date: "11/04", onLunarCal: false, name: "ユネスコ憲章記念日", since: 1946},
            {date: "11/04", onLunarCal: false, name: "いい推しの日", since: 2019},
            {date: "11/05", onLunarCal: false, name: "世界津波の日", since: 2015},
            {date: "11/05", onLunarCal: false, name: "いいりんごの日", since: 2001},
            {date: "11/06", onLunarCal: false, name: "アパート記念日", since: 1910},
            {date: "11/07", onLunarCal: false, name: "ココアの日", since: 2016},
            {date: "11/07", onLunarCal: false, name: "鍋の日", since: 2001},
            {date: "11/07", onLunarCal: false, name: "ソースの日", since: 2013},
            {date: "11/08", onLunarCal: false, name: "レントゲンの日", since: 2012},
            {date: "11/08", onLunarCal: false, name: "信楽たぬきの日", since: 2012},
            {date: "11/08", onLunarCal: false, name: "八ヶ岳の日", since: 2000},
            {date: "11/09", onLunarCal: false, name: "１１９番の日", since: 1987},
            {date: "11/09", onLunarCal: false, name: "いいオークの日", since: 2011},
            {date: "11/09", onLunarCal: false, name: "イーノックの日", since: 2010},
            {date: "11/10", onLunarCal: false, name: "エレベーターの日", since: 1979},
            {date: "11/10", onLunarCal: false, name: "トイレの日", since: 1986},
            {date: "11/11", onLunarCal: false, name: "電池の日", since: 1987},
            {date: "11/11", onLunarCal: false, name: "ジュエリーデー", since: 1986},
            {date: "11/11", onLunarCal: false, name: "ポッキー＆プリッツの日", since: 1999},
            {date: "11/11", onLunarCal: false, name: "きりたんぽの日", since: 2000},
            {date: "11/11", onLunarCal: false, name: "うまい棒の日", since: 2019},
            {date: "11/12", onLunarCal: false, name: "洋服の日", since: 1972},
            {date: "11/12", onLunarCal: false, name: "皮膚の日", since: 1989},
            {date: "11/12", onLunarCal: false, name: "いいにらの日", since: 2020},
            {date: "11/13", onLunarCal: false, name: "うるしの日", since: 1985},
            {date: "11/13", onLunarCal: false, name: "チーかまの日", since: 2019},
            {date: "11/14", onLunarCal: false, name: "世界糖尿病デー", since: 2006},
            {date: "11/14", onLunarCal: false, name: "アンチエイジングの日", since: 2007},
            {date: "11/w2-4", onLunarCal: false, name: "ギネス世界記録の日", since: 2005},
            {date: "11/15", onLunarCal: false, name: "こんぶの日", since: 1982},
            {date: "11/15", onLunarCal: false, name: "いいインコの日", since: 2018},
            {date: "11/16", onLunarCal: false, name: "幼稚園記念日", since: 1876},
            {date: "11/16", onLunarCal: false, name: "自然薯の日", since: 2009}, // Google、Twitter検索の最古の記述
            {date: "11/17", onLunarCal: false, name: "将棋の日", since: 1975},
            {date: "11/17", onLunarCal: false, name: "レンコンの日", since: 1994},
            {date: "11/18", onLunarCal: false, name: "雪見だいふくの日", since: 2006}, // Google検索の最古ページ
            {date: "11/18", onLunarCal: false, name: "防犯の日", since: 1962},
            {date: "11/18", onLunarCal: false, name: "ミッキーマウス", since: 1928, anniv: true},
            {date: "11/19", onLunarCal: false, name: "世界トイレの日", since: 2013},
            {date: "11/19", onLunarCal: false, name: "農協記念日", since: 1947},
            {date: "11/20", onLunarCal: false, name: "えびす講", since: 1989},
            {date: "11/20", onLunarCal: false, name: "毛皮の日", since: 1989},
            {date: "11/20", onLunarCal: false, name: "ピザの日", since: 1995},
            {date: "11/20", onLunarCal: false, name: "ウィンドウズ", since: 1985, anniv: true},
            {date: "11/21", onLunarCal: false, name: "インターネット記念日", since: 1969},
            {date: "11/21", onLunarCal: false, name: "フライドチキンの日", since: 2015},
            {date: "11/21", onLunarCal: false, name: "イーブイの日", since: 2018},
            {date: "11/21", onLunarCal: false, name: "スーパーファミコン", since: 1990, anniv: true},
            {date: "11/w3-4", onLunarCal: false, name: "ボジョレーヌーヴォー解禁", since: 1985},
            {date: "11/22", onLunarCal: false, name: "いい夫婦の日", since: 1998},
            {date: "11/22", onLunarCal: false, name: "長野県りんごの日", since: 1999},
            {date: "11/23", onLunarCal: false, name: "Ｊリーグの日", since: 1993},
            {date: "11/23", onLunarCal: false, name: "ゲームの日", since: 1999},
            {date: "11/23", onLunarCal: false, name: "牡蠣の日", since: 2003},
            {date: "11/24", onLunarCal: false, name: "鰹節の日", since: 1999},
            {date: "11/24", onLunarCal: false, name: "オペラ記念日", since: 1894},
            {date: "11/24", onLunarCal: false, name: "進化の日", since: 1859},
            {date: "11/25", onLunarCal: false, name: "ハイビジョンの日", since: 1987},
            {date: "11/25", onLunarCal: false, name: "ＯＬの日", since: 1994},
            {date: "11/26", onLunarCal: false, name: "いいプルーンの日", since: 2012}, // Google検索の最古ページ
            {date: "11/26", onLunarCal: false, name: "いい風呂の日", since: 2002}, // Google検索の最古ページ
            {date: "11/26", onLunarCal: false, name: "いいフォローの日", since: 2019},
            {date: "11/27", onLunarCal: false, name: "ノーベル賞制定記念日", since: 1901},
            {date: "11/27", onLunarCal: false, name: "いいフナの日", since: 2000},
            {date: "11/28", onLunarCal: false, name: "フランスパンの日", since: 2015},
            {date: "11/28", onLunarCal: false, name: "太平洋の日", since: null},
            {date: "11/29", onLunarCal: false, name: "いい肉球の日", since: 2005},
            {date: "11/30", onLunarCal: false, name: "年金の日", since: 2014},
            {date: "11/30", onLunarCal: false, name: "本みりんの日", since: 2008}, // 全国味淋協会HP開設年
        ],
        12: [
            {date: "12/08", onLunarCal: false, name: "こと納め"},
            {date: "12/08", onLunarCal: true, name: "旧こと納め"},
            {date: "12/13", onLunarCal: false, name: "正月こと始め"},
            {date: "12/13", onLunarCal: true, name: "旧正月こと始め"},
            {date: "12/21", onLunarCal: false, name: "締めの大師"},
            {date: "12/24", onLunarCal: false, name: "納めの地蔵"},
            {date: "12/31", onLunarCal: false, name: "大晦日"},
            {date: "12/31", onLunarCal: false, name: "除夜"},
    
            {date: "12/01", onLunarCal: false, name: "世界エイズデー", since: 1988},
            {date: "12/01", onLunarCal: false, name: "映画の日", since: 1956},
            {date: "12/01", onLunarCal: false, name: "カイロの日", since: 1991},
            {date: "12/01", onLunarCal: false, name: "ワッフルの日", since: 2016},
            {date: "12/02", onLunarCal: false, name: "日本人宇宙飛行記念日", since: 1990},
            {date: "12/02", onLunarCal: false, name: "ビフィズス菌の日", since: 2016},
            {date: "12/02", onLunarCal: false, name: "Ｗｉｉ", since: 2006, anniv: true},
            {date: "12/03", onLunarCal: false, name: "プレイステーション", since: 1994, anniv: true},
            {date: "12/03", onLunarCal: false, name: "カレンダーの日", since: 1987},
            {date: "12/03", onLunarCal: false, name: "みかんの日", since: 2004}, // Google検索の最古ページ
            {date: "12/04", onLunarCal: false, name: "Ｅ．Ｔ．の日", since: 1982},
            {date: "12/05", onLunarCal: false, name: "バミューダ<wbr>トライアングルの日", since: 1982},
            {date: "12/05", onLunarCal: false, name: "アルバムの日", since: 2010},
            {date: "12/06", onLunarCal: false, name: "音の日", since: 1994},
            {date: "12/06", onLunarCal: false, name: "姉の日", since: 1992},
            {date: "12/06", onLunarCal: false, name: "シンフォニー記念日", since: 1965}, // 山田耕筰没年
            {date: "12/07", onLunarCal: false, name: "神戸港開港記念日", since: 1867},
            {date: "12/07", onLunarCal: false, name: "クリスマスツリーの日", since: 1886},
            {date: "12/08", onLunarCal: false, name: "太平洋戦争開戦記念日", since: 1941},
            {date: "12/08", onLunarCal: false, name: "日刊新聞創刊日", since: 1871},
            {date: "12/09", onLunarCal: false, name: "鍛高譚の日", since: 2017},
            {date: "12/09", onLunarCal: false, name: "マウスの誕生日", since: 2018},
            {date: "12/10", onLunarCal: false, name: "ノーベル賞授賞式", since: 1901},
            {date: "12/10", onLunarCal: false, name: "アロエヨーグルトの日", since: 1994},
            {date: "12/10", onLunarCal: false, name: "ベルトの日", since: 2018},
            {date: "12/11", onLunarCal: false, name: "ユニセフ創立記念日", since: 1946},
            {date: "12/11", onLunarCal: false, name: "国際山岳デー", since: 2003},
            {date: "12/12", onLunarCal: false, name: "漢字の日", since: 1995},
            {date: "12/12", onLunarCal: false, name: "ダースの日", since: 1993},
            {date: "12/12", onLunarCal: false, name: "ニコニコ動画", since: 2006, anniv: true},
            {date: "12/13", onLunarCal: false, name: "双子の日", since: 1874},
            {date: "12/13", onLunarCal: false, name: "ビタミンの日", since: 2000},
            {date: "12/14", onLunarCal: false, name: "南極の日", since: 1911},
            {date: "12/14", onLunarCal: false, name: "忠臣蔵の日", since: null},
            {date: "12/15", onLunarCal: false, name: "年賀郵便特別扱い開始日", since: 1906},
            {date: "12/16", onLunarCal: false, name: "電話創業の日", since: 1890},
            {date: "12/16", onLunarCal: false, name: "紙の記念日", since: 1875},
            {date: "12/16", onLunarCal: false, name: "トロの日", since: 2016},
            {date: "12/17", onLunarCal: false, name: "飛行機の日", since: 1903},
            {date: "12/18", onLunarCal: false, name: "東京駅完成記念日", since: 1914},
            {date: "12/18", onLunarCal: false, name: "国連加盟記念日", since: 1956},
            {date: "12/18", onLunarCal: false, name: "ファイナルファンタジー", since: 1987, anniv: true},
            {date: "12/19", onLunarCal: false, name: "日本初飛行の日", since: 1910},
            {date: "12/20", onLunarCal: false, name: "果ての二十日", since: null},
            {date: "12/20", onLunarCal: false, name: "ブリの日", since: 2004}, // Google検索の最古ページ
            {date: "12/21", onLunarCal: false, name: "クロスワードの日", since: 1925}, // 日本での連載開始年
            {date: "12/21", onLunarCal: false, name: "回文の日", since: 2008}, // Google検索の最古ページ
            {date: "12/22", onLunarCal: false, name: "スープの日", since: 2020},
            {date: "12/22", onLunarCal: false, name: "ジェネリック医薬品の日", since: 2019},
            {date: "12/23", onLunarCal: false, name: "上皇誕生日", since: 2019},
            {date: "12/23", onLunarCal: false, name: "東京タワー完成の日", since: 1958},
            {date: "12/23", onLunarCal: false, name: "テレホンカードの日", since: 1982},
            {date: "12/24", onLunarCal: false, name: "クリスマスイブ", since: 1874},
            {date: "12/25", onLunarCal: false, name: "クリスマス", since: 1874},
            {date: "12/25", onLunarCal: false, name: "昭和改元の日", since: 1875},
            {date: "12/25", onLunarCal: false, name: "スケートの日", since: 1982},
            {date: "12/26", onLunarCal: false, name: "プロ野球誕生の日", since: 1934},
            {date: "12/26", onLunarCal: false, name: "ジャイアンツ創立", since: 1934, anniv: true},
            {date: "12/27", onLunarCal: false, name: "鏡音リン・レン記念日", since: 2007},
            {date: "12/27", onLunarCal: false, name: "浅草仲見世記念日", since: 1885},
            {date: "12/28", onLunarCal: false, name: "ディスクジョッキーの日", since: 1999},
            {date: "12/28-wd", onLunarCal: false, name: "官公庁御用納め", since: 1873},
            {date: "12/29", onLunarCal: false, name: "清水トンネル貫通記念日", since: 1929},
            {date: "12/29", onLunarCal: false, name: "福の日", since: 2013},
            {date: "12/29", onLunarCal: false, name: "シャンソンの日", since: 1990},
            {date: "12/30-wd", onLunarCal: false, name: "取引所大納会", since: 1983},
            {date: "12/30", onLunarCal: false, name: "地下鉄記念日", since: 1927},
        ],

        monthly: [
            {date: "**/15", onLunarCal: false, name: "お菓子の日", since: 1981},
            {date: "**/LAST", onLunarCal: false, name: "そばの日", since: 1983},
        ]
    };
}